name: Deploy RDP via Ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_rdp:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Ngrok
      run: |
        brew install --cask ngrok

    - name: Configure macOS Remote Desktop (Screen Sharing)
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
        -activate -configure -access -on -users "$USER" -privs -all \
        -restart -agent -menu

    - name: Start Ngrok tunnel for RDP (port 3389)
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
        ngrok authtoken $NGROK_TOKEN
        ngrok tcp 3389 > ngrok_output.log &
        sleep 5
        cat ngrok_output.log

    - name: Display Ngrok tunnel URL
      run: |
        TUNNEL_URL=$(grep -o "tcp://[0-9a-z\.]*:[0-9]*" ngrok_output.log)
        echo "Ngrok tunnel is ready: $TUNNEL_URL"
        echo "::set-output name=ngrok_url::$TUNNEL_URL"
